### ISSUE TITLE
Should we rebuild the list on every login?

### ISSUE THREAD

**Issue by JohnnyP10** [wharton/penndjangosaml2#7]
I noticed permissions will stay with the user if you change the groups imported by the INCLUDE_PENNGROUPS setting.

I think we should rebuild all PennGroups and provide a way of keeping the group membership with the app separate or we just need to better understand Grouper and create a PennGroup for each App that we can assign people to by a union of groups or individual basis.

**Comment by sturoscy** [comment]
This is a hot issue. I agree that we should think about creating a group for each app (if needed), but there are a lot of different scenarios for authorization here. I suppose we could have the user set something like an APP_GROUP setting along with what other groups memberships should be pulled from (ADDTIONAL_PENN_GROUPS or something similar to that).
